#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if type go > /dev/null; then
  export GOPATH="$HOME/go"
  export PATH="$(go env GOPATH)/bin:$PATH"
fi
# Cargo packages
if type cargo > /dev/null; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi
# Yarn packages
if type yarn > /dev/null; then
  export PATH="$HOME/.yarn/bin:$PATH"
fi

export PATH="$HOME/.local/bin:$PATH"
export MANPATH="$HOME/.local/share/man:$MANPATH"


# Wraps mc so that it exits to the directory I'm looking at.
alias mc='. /usr/share/mc/bin/mc-wrapper.sh'

alias dk=docker
alias dkr="docker run"
alias dkb="docker build"
alias dkm=docker-machine
alias dkc=docker-compose

alias bfg='java -jar /usr/lib/bfg-1.12.15.jar'

alias cg='cd $(git rev-parse --show-toplevel)'

export LESS='-i -M -R'
export EDITOR='nvim'

cdr() {
  tmpfile="/tmp/ranger-dir"
  ranger --choosedir=$tmpfile $argv
  rangerdir=$(cat $tmpfile)
  if [[ $PWD != $rangerdir ]]; then
    cd $rangerdir
    unset rangerdir
  fi
}

alias rr=ranger

if type thefuck > /dev/null; then
  eval $(thefuck --alias damn)
fi

if type kubectl > /dev/null; then
  source <(kubectl completion zsh)
fi

if [[ -e /usr/local/share/z/z.sh ]]; then
  source /usr/local/share/z/z.sh
fi

export DEFAULT_USER=`id -un`
